{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-dash",
    "version": "2.18.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-dash-2.18.7.aar",
          "url": "exoplayer-dash-2.18.7.aar",
          "size": 131515,
          "sha512": "6ed857de413f61d29f549c948045d7b8484098847f1e7d63762bdbfbcf81e8dfed2a7286c693765c67060c3fd0d72ff571e157ec680e56b7fc5e8336aed058f2",
          "sha256": "ad6a2da729e32c114b52cbba711ef322123ba7a33702483f5b4ea113a0982301",
          "sha1": "e82dcaeb8424bb42c41855352f3ef8c68cb4cc8e",
          "md5": "7f225e4b8b733ac6ec5da5764fdc7493"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-dash-2.18.7.aar",
          "url": "exoplayer-dash-2.18.7.aar",
          "size": 131515,
          "sha512": "6ed857de413f61d29f549c948045d7b8484098847f1e7d63762bdbfbcf81e8dfed2a7286c693765c67060c3fd0d72ff571e157ec680e56b7fc5e8336aed058f2",
          "sha256": "ad6a2da729e32c114b52cbba711ef322123ba7a33702483f5b4ea113a0982301",
          "sha1": "e82dcaeb8424bb42c41855352f3ef8c68cb4cc8e",
          "md5": "7f225e4b8b733ac6ec5da5764fdc7493"
        }
      ]
    }
  ]
}
