{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media2",
    "module": "media2-common",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "media2-common-1.2.1.aar",
          "url": "media2-common-1.2.1.aar",
          "size": 52661,
          "sha512": "4b2c845bf54178aed1525173de1819a6e76ac401341deeb350471f229979c3fc6711462cd3aff405be2fc29f0888aead638d0ed8b1b478a381b680b1011db226",
          "sha256": "3912a9c9ec81f85f0b661e259e4c468872a2ffcf89cf238d325808a89958e0ea",
          "sha1": "677443e44207ad970009b37067525c475b6b894a",
          "md5": "b1c3d782b69c5cba1a5f57c4f6a5152b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "media2-common-1.2.1.aar",
          "url": "media2-common-1.2.1.aar",
          "size": 52661,
          "sha512": "4b2c845bf54178aed1525173de1819a6e76ac401341deeb350471f229979c3fc6711462cd3aff405be2fc29f0888aead638d0ed8b1b478a381b680b1011db226",
          "sha256": "3912a9c9ec81f85f0b661e259e4c468872a2ffcf89cf238d325808a89958e0ea",
          "sha1": "677443e44207ad970009b37067525c475b6b894a",
          "md5": "b1c3d782b69c5cba1a5f57c4f6a5152b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media2-common-1.2.1-sources.jar",
          "url": "media2-common-1.2.1-sources.jar",
          "size": 41925,
          "sha512": "5547f0fbad6c76a2c2b0fb3f604c86f5dc2bd77ff5fc34c5cf7a57ee7d518ebd7b843f2b259b24ad05fcd4e80454fb5591bd653b82454f5190a648b0c7dd963e",
          "sha256": "55c9c658d31e08d025d362300582b7b842a32a31b3c4a4891d6b7019b7c30f79",
          "sha1": "39dfa111f1f0bb8586d79aa7c9a6e7fd613ed282",
          "md5": "51499e220358070ed19d0741dfe15d99"
        }
      ]
    }
  ]
}
