{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-database",
    "version": "2.18.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-database-2.18.7.aar",
          "url": "exoplayer-database-2.18.7.aar",
          "size": 7332,
          "sha512": "2f54e047f1f06353646137416d5a3d225436f52cd055cb204ed94a1c2c5275559207e363b7f2f7cd53d5c8136f6238aff2747fe0526e29284ec929c94a4c0ded",
          "sha256": "31f0929246fb81296345be8414e7fa080a82deb8d382eb5d875974649030619d",
          "sha1": "13494fd39372dc9278a993afc71884cc6c0c51e6",
          "md5": "8c2db0781ec04016b40ae8bf763f7282"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-database-2.18.7.aar",
          "url": "exoplayer-database-2.18.7.aar",
          "size": 7332,
          "sha512": "2f54e047f1f06353646137416d5a3d225436f52cd055cb204ed94a1c2c5275559207e363b7f2f7cd53d5c8136f6238aff2747fe0526e29284ec929c94a4c0ded",
          "sha256": "31f0929246fb81296345be8414e7fa080a82deb8d382eb5d875974649030619d",
          "sha1": "13494fd39372dc9278a993afc71884cc6c0c51e6",
          "md5": "8c2db0781ec04016b40ae8bf763f7282"
        }
      ]
    }
  ]
}
