{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-extractor",
    "version": "2.18.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-extractor-2.18.7.aar",
          "url": "exoplayer-extractor-2.18.7.aar",
          "size": 712453,
          "sha512": "d3eb28d26d9a6246f26b7feed19d9d8da96680c20faeaa969c6e3bc30e3cc103ed5039900cb4e8109e983c58f5d155bdebd79312733cea0c294268e7b5d8fbce",
          "sha256": "c3e34c7b07ecd3c78a75bb7185671030bea4371ac88d854000a856fc05f7eeff",
          "sha1": "932de11c455b0c89d6873b53746d55e2096d7f3d",
          "md5": "a6370effbd400b8f668d45d482eed3a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.18.7"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-extractor-2.18.7.aar",
          "url": "exoplayer-extractor-2.18.7.aar",
          "size": 712453,
          "sha512": "d3eb28d26d9a6246f26b7feed19d9d8da96680c20faeaa969c6e3bc30e3cc103ed5039900cb4e8109e983c58f5d155bdebd79312733cea0c294268e7b5d8fbce",
          "sha256": "c3e34c7b07ecd3c78a75bb7185671030bea4371ac88d854000a856fc05f7eeff",
          "sha1": "932de11c455b0c89d6873b53746d55e2096d7f3d",
          "md5": "a6370effbd400b8f668d45d482eed3a9"
        }
      ]
    }
  ]
}
