{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-java",
    "version": "1.0.0-beta04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0-beta04"
          }
        }
      ],
      "files": [
        {
          "name": "window-java-1.0.0-beta04.aar",
          "url": "window-java-1.0.0-beta04.aar",
          "size": 7304,
          "sha512": "953f30b7ee30c67e8ee54a6e5a480be30c832588beea080c66f82d3d0b34dd6e0d5625906c545d9c7d581eb9b990b6b1b1a5ffc1f847efa77584fbdd69ce19f4",
          "sha256": "1c2669a75f6017bd45e443361f28c28428652b985f65f15b85ab5fe792a7b816",
          "sha1": "ef1688d892f6dc05c9e1568cbb6355d35f2428d6",
          "md5": "c997a4db724952b3b724daf25ad7f781"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0-beta04"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "window-java-1.0.0-beta04.aar",
          "url": "window-java-1.0.0-beta04.aar",
          "size": 7304,
          "sha512": "953f30b7ee30c67e8ee54a6e5a480be30c832588beea080c66f82d3d0b34dd6e0d5625906c545d9c7d581eb9b990b6b1b1a5ffc1f847efa77584fbdd69ce19f4",
          "sha256": "1c2669a75f6017bd45e443361f28c28428652b985f65f15b85ab5fe792a7b816",
          "sha1": "ef1688d892f6dc05c9e1568cbb6355d35f2428d6",
          "md5": "c997a4db724952b3b724daf25ad7f781"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "window-java-1.0.0-beta04-sources.jar",
          "url": "window-java-1.0.0-beta04-sources.jar",
          "size": 2103,
          "sha512": "583ad40069e87ceffaba23d904127397e401f2cd55e60cd092404c11b2ce6a11670ea89e999f7b1f724d49c71cffb50bde3d33e08f265642e0f9f982b95234dc",
          "sha256": "6bf66b83f642d5417ae1e32e0773762b0f4eedd6ccc1607d024f67078ec829e2",
          "sha1": "aebe0d5dd92117437900757652f05fd10dc45382",
          "md5": "b9fe233b6fda5bfc7e4d4ecc9bd5251b"
        }
      ]
    }
  ]
}
