{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-hls",
    "version": "2.18.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-hls-2.18.7.aar",
          "url": "exoplayer-hls-2.18.7.aar",
          "size": 159542,
          "sha512": "ba61b50a27422e3594fd756d1272fb91cb056db27bab2f056cebeba5854ead63cd2b95051b1e44c2959cf5b22fd8c8e06d84b9acfe3db6770a4dc0ff2fcad334",
          "sha256": "d34a008fdb0fedc50244481ec5601a3e3f4ea281cb44eb435f65dca8680c8855",
          "sha1": "3c2fac4c07c693a558114e4d2db715937f267da0",
          "md5": "88861acc2b919e806232aa4b5f8a7e97"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.7"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-hls-2.18.7.aar",
          "url": "exoplayer-hls-2.18.7.aar",
          "size": 159542,
          "sha512": "ba61b50a27422e3594fd756d1272fb91cb056db27bab2f056cebeba5854ead63cd2b95051b1e44c2959cf5b22fd8c8e06d84b9acfe3db6770a4dc0ff2fcad334",
          "sha256": "d34a008fdb0fedc50244481ec5601a3e3f4ea281cb44eb435f65dca8680c8855",
          "sha1": "3c2fac4c07c693a558114e4d2db715937f267da0",
          "md5": "88861acc2b919e806232aa4b5f8a7e97"
        }
      ]
    }
  ]
}
