{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-smoothstreaming",
    "version": "2.18.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-smoothstreaming-2.18.7.aar",
          "url": "exoplayer-smoothstreaming-2.18.7.aar",
          "size": 46882,
          "sha512": "06016f2a65bcf1bcc13676db784bead56ac0f342234ef68c67a73ea75718d8ae0fc33c576173744878aad313539ec44b321dcda8fa037af044f47800be83c313",
          "sha256": "7e15ba782aef1e200fa1e0a48ed636b8b6e49f0658b4b4f525a38cf8d5ab4007",
          "sha1": "3c73b8620b24ed56068669c897f621acf1f85efe",
          "md5": "7dfd95bb7981d84f71165f8c41938bad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-smoothstreaming-2.18.7.aar",
          "url": "exoplayer-smoothstreaming-2.18.7.aar",
          "size": 46882,
          "sha512": "06016f2a65bcf1bcc13676db784bead56ac0f342234ef68c67a73ea75718d8ae0fc33c576173744878aad313539ec44b321dcda8fa037af044f47800be83c313",
          "sha256": "7e15ba782aef1e200fa1e0a48ed636b8b6e49f0658b4b4f525a38cf8d5ab4007",
          "sha1": "3c73b8620b24ed56068669c897f621acf1f85efe",
          "md5": "7dfd95bb7981d84f71165f8c41938bad"
        }
      ]
    }
  ]
}
