{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media",
    "module": "media",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-1.4.1.aar",
          "url": "media-1.4.1.aar",
          "size": 342889,
          "sha512": "73b90306667a9f5e36301451f303ac8a2666575e82e2802cb75cd2027e9a847ae2d89423bfc200dbb742c9c7ee40db69623b111e6d812b0cc2f4e7227910850d",
          "sha256": "fdfb2f93b23895341ed547ffb26e1f708d9d20e3cd8e73bb6590e4a7131fd60f",
          "sha1": "cc4e5a383a5487cd4c5289c1ab87a0bbb3d2ddac",
          "md5": "c693e09468262627d9e066d3529f681d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-1.4.1.aar",
          "url": "media-1.4.1.aar",
          "size": 342889,
          "sha512": "73b90306667a9f5e36301451f303ac8a2666575e82e2802cb75cd2027e9a847ae2d89423bfc200dbb742c9c7ee40db69623b111e6d812b0cc2f4e7227910850d",
          "sha256": "fdfb2f93b23895341ed547ffb26e1f708d9d20e3cd8e73bb6590e4a7131fd60f",
          "sha1": "cc4e5a383a5487cd4c5289c1ab87a0bbb3d2ddac",
          "md5": "c693e09468262627d9e066d3529f681d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media-1.4.1-sources.jar",
          "url": "media-1.4.1-sources.jar",
          "size": 143793,
          "sha512": "05b86cfc2ca0dffc1ac1b7943aef9dba21a6338e20bf6ff7360bc142c42cb41578297a28099d47b3da6363dde6db8957cd87822aa0987503202efc8f39015d19",
          "sha256": "56dcaf09dd9dfa906c3e862cf861d6162637dbd71619c65db6ff717470a457a7",
          "sha1": "d56562ca7df624433ca01f52f255c035084a486d",
          "md5": "1f1490fd66e92cb2baa957ea52e0d523"
        }
      ]
    }
  ]
}
