{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-datasource",
    "version": "2.18.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-datasource-2.18.7.aar",
          "url": "exoplayer-datasource-2.18.7.aar",
          "size": 139994,
          "sha512": "8a06509030613b878e25b0f513e2429b670bc38d086115843783e469d2150fd07dd2968c78654d56510c3ca7565d938c0e31118f7eb6f076ee81b8d3385ae1cc",
          "sha256": "cbe67ad9eaf94be7b35d1a625252a79ed5c18601d19f7b4d787acfbcea009208",
          "sha1": "915e6b7f8f3dae660f595567d395aa3d3ad56730",
          "md5": "3be70f5e814bf77bada9578b3ad097f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-datasource-2.18.7.aar",
          "url": "exoplayer-datasource-2.18.7.aar",
          "size": 139994,
          "sha512": "8a06509030613b878e25b0f513e2429b670bc38d086115843783e469d2150fd07dd2968c78654d56510c3ca7565d938c0e31118f7eb6f076ee81b8d3385ae1cc",
          "sha256": "cbe67ad9eaf94be7b35d1a625252a79ed5c18601d19f7b4d787acfbcea009208",
          "sha1": "915e6b7f8f3dae660f595567d395aa3d3ad56730",
          "md5": "3be70f5e814bf77bada9578b3ad097f4"
        }
      ]
    }
  ]
}
