{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-decoder",
    "version": "2.18.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-decoder-2.18.7.aar",
          "url": "exoplayer-decoder-2.18.7.aar",
          "size": 17089,
          "sha512": "04f84644c67e3b286a3bead99be4c077f0858ff60165ea89cc9c5161ae9b91b4b003b72619e89ddc6a17003166996da85110b5cba532baef272033dc579af363",
          "sha256": "598c0b444db71770f9b89b4e444e34cb03d5ed2eb5c12fb062afb2f9b05b9a1e",
          "sha1": "8d811a1a2d017dcc9dd21c36910caf76e2d515f0",
          "md5": "466ae6cdcf1c1f966b469361bdc043f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-decoder-2.18.7.aar",
          "url": "exoplayer-decoder-2.18.7.aar",
          "size": 17089,
          "sha512": "04f84644c67e3b286a3bead99be4c077f0858ff60165ea89cc9c5161ae9b91b4b003b72619e89ddc6a17003166996da85110b5cba532baef272033dc579af363",
          "sha256": "598c0b444db71770f9b89b4e444e34cb03d5ed2eb5c12fb062afb2f9b05b9a1e",
          "sha1": "8d811a1a2d017dcc9dd21c36910caf76e2d515f0",
          "md5": "466ae6cdcf1c1f966b469361bdc043f3"
        }
      ]
    }
  ]
}
